# -*- coding: utf-8 -*-
"""V3_M01_V1_ENGINE_CHANGE_ATTRIBUTION_R1 — READ-ONLY forensic attribution of trader_v1/engine.py.

Answers ONLY: what changed, when, and by which mechanism. No repair, no baseline change, no whitelist,
no runtime-class widening, no commit. Writes only under m01_v1_engine_attribution_r1/.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
ENGINE = os.path.dirname(HERE)
RE = os.path.dirname(ENGINE)
AIQ = os.path.dirname(RE)
MVR1 = os.path.join(ENGINE, "mv_r1")
TARGET = "research/hermes/trader_v1/engine.py"
FULL = os.path.join(AIQ, TARGET)
NOW = datetime.now(timezone.utc).isoformat()
sys.stdout.reconfigure(encoding="utf-8", errors="replace")
A = {}


def sh(*a, cwd=None):
    r = subprocess.run(list(a), cwd=cwd or AIQ, capture_output=True, text=True, encoding="utf-8", errors="replace")
    return ((r.stdout or "") + (r.stderr or "")).strip()


def sha_file(p):
    return hashlib.sha256(open(p, "rb").read()).hexdigest()


def ts(sec):
    return datetime.fromtimestamp(sec, timezone.utc).isoformat() if sec else None


def main():
    os.makedirs(HERE, exist_ok=True)
    # ---------------- §4 git status audit (read-only) ----------------
    st = sh("git", "status", "--short", "--", TARGET)
    diff = sh("git", "diff", "--", TARGET)
    diff_cached = sh("git", "diff", "--cached", "--", TARGET)
    numstat = sh("git", "diff", "--numstat", "--", TARGET)
    log = sh("git", "log", "--follow", "--format=%H|%ad|%s", "--date=iso", "-5", "--", TARGET)
    head_blob = sh("git", "rev-parse", f"HEAD:{TARGET}")
    work_blob = sh("git", "hash-object", TARGET)
    A["git"] = {"status_short": st or "(clean)", "diff_present": bool(diff), "diff_cached_present": bool(diff_cached),
                 "numstat": numstat or "(none)", "log_follow_last5": log.splitlines() if log else [],
                 "HEAD_blob": head_blob, "worktree_blob": work_blob, "blob_equal": head_blob == work_blob,
                 "HEAD": sh("git", "rev-parse", "--short", "HEAD")}
    # diff summary
    adds = dels = hunks = 0
    syms = set()
    for l in diff.splitlines():
        if l.startswith("@@"):
            hunks += 1
        elif l.startswith("+++") or l.startswith("---"):
            continue
        elif l.startswith("+"):
            adds += 1
        elif l.startswith("-"):
            dels += 1
    for l in diff.splitlines():
        if l[:1] in "+-" and not l.startswith(("+++", "---")):
            for m in re.findall(r"\b[A-Za-z_][A-Za-z0-9_]{2,}\b", l):
                syms.add(m)
    class_hint = "UNKNOWN"
    blob = diff.lower()
    if any(k in blob for k in ("order_send", "stop_loss", "take_profit", "risk", "position", "lot", "magic",
                                 "def execute", "def decide", "strategy", "signal")):
        class_hint = "A_STRATEGY_OR_TRADE_OR_RISK_LOGIC"
    elif any(k in blob for k in ("run_state", "state.json", "ledger", "json.dump", "timestamp", "generated")):
        class_hint = "B_AUTOGENERATED_OR_STATE_WRITEBACK"
    A["diff_summary"] = {"LINES_ADDED": adds, "LINES_DELETED": dels, "HUNKS": hunks,
                           "CHANGED_SYMBOLS": sorted(syms)[:40], "CHANGE_KIND_HINT": class_hint,
                           "diff_head": diff[:1200]}

    # ---------------- §4/§5 hashes + timeline ----------------
    base = json.load(open(os.path.join(MVR1, "WORKTREE_BASELINE_MV_R1.json"), encoding="utf-8"))
    BASELINE_SHA = base["isolation_baseline"]["trader_v1"]["files"].get(TARGET)
    BASELINE_TIME = base["ts_utc"]
    CURRENT_SHA = sha_file(FULL)
    stt = os.stat(FULL)
    mvr1_sum = json.load(open(os.path.join(MVR1, "run_summary.json"), encoding="utf-8"))
    TASK_START = mvr1_sum.get("ts_utc")
    A["hashes"] = {"BASELINE_SHA256": BASELINE_SHA, "CURRENT_SHA256": CURRENT_SHA,
                    "MATCH": BASELINE_SHA == CURRENT_SHA, "HEAD_blob_hash_object": HEAD2 if False else None}
    A["timeline"] = {"BASELINE_TIME": BASELINE_TIME, "TASK_START_TIME": TASK_START,
                      "CURRENT_MTIME": ts(stt.st_mtime), "CURRENT_CTIME": ts(stt.st_ctime),
                      "ISOLATION_SCAN_TIME": NOW,
                      "mtime_after_baseline": stt.st_mtime > datetime.fromisoformat(BASELINE_TIME).timestamp(),
                      "mtime_before_task_start": stt.st_mtime < datetime.fromisoformat(TASK_START).timestamp()}
    print("§4/§5:", json.dumps({"baseline_match": A["hashes"]["MATCH"], "status": A["git"]["status_short"][:80],
                                  "blob_equal": A["git"]["blob_equal"], "mtime": A["timeline"]["CURRENT_MTIME"],
                                  "baseline_time": BASELINE_TIME, "task_start": TASK_START,
                                  "adds": adds, "dels": dels, "hunks": hunks,
                                  "kind": class_hint}, ensure_ascii=False), flush=True)

    # ---------------- §7 evidence search: any mechanism that WRITES engine.py ----------------
    wpat = re.compile(r"(open\s*\([^)]*engine\.py[^)]*['\"](w|a|wb|ab)['\"]|write_text\s*\(|shutil\.copy[^)]*engine\.py"
                       r"|to_engine|update_engine|sync_engine|deploy_engine)")
    hits = []
    for root in (os.path.join(RE, "hermes"), os.path.join(AIQ, "tools"), os.path.join(AIQ, "scripts")):
        if not os.path.isdir(root):
            continue
        for r_, _, fs in os.walk(root):
            if "__pycache__" in r_ or ".git" in r_:
                continue
            for f in fs:
                if not f.lower().endswith((".py", ".ps1", ".bat", ".cmd", ".sh", ".json", ".yaml", ".yml")):
                    continue
                p = os.path.join(r_, f)
                try:
                    txt = open(p, encoding="utf-8", errors="ignore").read()
                except Exception:  # noqa: BLE001
                    continue
                for m in wpat.finditer(txt):
                    line = txt[:m.start()].count("\n") + 1
                    hits.append({"file": os.path.relpath(p, AIQ).replace("\\", "/"), "line": line,
                                  "match": m.group(0)[:120]})
                if len(hits) > 60:
                    break
    A["write_mechanism_search"] = {"hits": len(hits), "examples": hits[:10]}
    # log evidence: any log file mentioning engine.py being written
    loghits = []
    for root in (os.path.join(RE, "hermes", "trader_v1"), os.path.join(AIQ, ".openclaw")):
        if not os.path.isdir(root):
            continue
        for r_, _, fs in os.walk(root):
            if "__pycache__" in r_:
                continue
            for f in fs:
                if not f.lower().endswith((".log", ".txt", ".jsonl")):
                    continue
                p = os.path.join(r_, f)
                try:
                    if os.path.getsize(p) > 4_000_000:
                        continue
                    txt = open(p, encoding="utf-8", errors="ignore").read()
                except Exception:  # noqa: BLE001
                    continue
                if "engine.py" in txt and any(k in txt.lower() for k in ("writ", "updat", "rewrote", "deploy",
                                                                          "sync", "generated")):
                    loghits.append(os.path.relpath(p, AIQ).replace("\\", "/"))
                if len(loghits) > 10:
                    break
    A["log_evidence"] = {"logs_mentioning_engine_py_write": loghits}

    # ---------------- §8 classification (strict, evidence-based) ----------------
    in_window = A["timeline"]["mtime_after_baseline"]
    has_write_mech = len(hits) > 0
    git_tracked_modified = st.startswith(" M") or st.startswith("M ")
    diff_present = A["git"]["diff_present"]
    reasons = []
    if not A["hashes"]["MATCH"]:
        reasons.append("BASELINE_SHA256 != CURRENT_SHA256 (engine.py content differs from the MV-R1 baseline)")
    if in_window:
        reasons.append("CURRENT_MTIME is AFTER BASELINE_TIME -> the write happened at/after the MV-R1 baseline")
    else:
        reasons.append("CURRENT_MTIME is BEFORE BASELINE_TIME (mtime alone is time evidence only)")
    if git_tracked_modified and diff_present:
        reasons.append("git: engine.py is a TRACKED-MODIFIED worktree file (uncommitted diff vs HEAD)")
    if has_write_mech:
        reasons.append(f"found {len(hits)} candidate code paths that could write engine.py (needs runtime proof)")
    # decision
    if not A["hashes"]["MATCH"] and (not in_window) and not has_write_mech and git_tracked_modified:
        cls = "HISTORICAL_DIRTY_CONFIRMED"
    elif not A["hashes"]["MATCH"] and in_window and has_write_mech:
        cls = "EXTERNAL_CHANGE_CONFIRMED"      # a mechanism exists but no in-window runtime proof yet
    else:
        cls = "UNRESOLVED"
    A["classification"] = {"CHANGE_CLASS": cls, "EVIDENCE": reasons,
                            "historical_dirty_test": {"mtime_predates_window": not in_window,
                                                        "git_tracked_modified_uncommitted": git_tracked_modified,
                                                        "no_write_mechanism_found": not has_write_mech},
                            "V1_RUNTIME_WRITE_PROVEN": False,
                            "note": "no runtime proof that V1 wrote the file in this window; only a mechanism search"},
    A["STATUS"] = "CONFIRMED" if cls != "UNRESOLVED" else "UNRESOLVED"
    A["BASELINE_POLICY_REVIEW_REQUIRED"] = (cls == "HISTORICAL_DIRTY_CONFIRMED")
    A["V1_SOURCE_CONFIG_CHANGED"] = "YES" if not A["hashes"]["MATCH"] else "NO"
    A["V2_SOURCE_CONFIG_CHANGED"] = "NO"
    A["RESEARCH_ARTIFACTS"] = "UNCHANGED"
    A["COMMIT"] = "NONE"
    A["ORDER_SEND"] = 0
    A["CANDIDATE"] = 0
    A["FORWARD"] = A["SHADOW"] = A["LIVE"] = "OFF"
    A["ts_utc"] = NOW
    json.dump(A, open(os.path.join(HERE, "attribution_summary.json"), "w", encoding="utf-8", newline="\n"), indent=1,
              ensure_ascii=False)
    out = {"V3_M01_V1_ENGINE_CHANGE_ATTRIBUTION_R1": A["STATUS"],
            "BASELINE_SHA256": BASELINE_SHA, "CURRENT_SHA256": CURRENT_SHA,
            "BASELINE_TIME": BASELINE_TIME, "CURRENT_MTIME": A["timeline"]["CURRENT_MTIME"],
            "CURRENT_CTIME": A["timeline"]["CURRENT_CTIME"], "TASK_START_TIME": TASK_START,
            "GIT_STATUS": A["git"]["status_short"], "GIT_DIFF": "PRESENT" if diff_present else "NONE",
            "GIT_DIFF_SUMMARY": {"LINES_ADDED": adds, "LINES_DELETED": dels, "HUNKS": hunks,
                                   "CHANGED_SYMBOLS": sorted(syms)[:20], "KIND_HINT": class_hint},
            "CHANGE_CLASS": cls, "EVIDENCE": reasons,
            "WRITE_MECHANISM_HITS": len(hits), "LOG_EVIDENCE": loghits[:5],
            "V1_SOURCE_CONFIG_CHANGED": A["V1_SOURCE_CONFIG_CHANGED"], "V2_SOURCE_CONFIG_CHANGED": "NO",
            "RESEARCH_ARTIFACTS": "UNCHANGED", "COMMIT": "NONE", "ORDER_SEND": 0, "CANDIDATE": 0,
            "FORWARD": "OFF", "SHADOW": "OFF", "LIVE": "OFF"}
    print("\n=== V1 ENGINE CHANGE ATTRIBUTION ===\n" + json.dumps(out, ensure_ascii=False, indent=1)[:2600], flush=True)


if __name__ == "__main__":
    main()
