# -*- coding: utf-8 -*-
"""V1-R3 — BLIND EVALUATOR + LEDGER + TESTS + AUDIT + FINAL REPORT/JSON (§27–§34, §55, §93–§96, §102–§111).

Hermes forecasts are produced elsewhere and are READ-ONLY here. Ground truth is generated by the
independent evaluator module only. No returns/PnL anywhere. Writes ONLY under v1_r3_hermes_market_forecast/.
"""
from __future__ import annotations

import collections
import hashlib
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:  # noqa: BLE001
    pass

REPO = r"C:\AIQuant"
ROOT = os.path.join(REPO, "research", "hermes", "trader_v1", "v1_r3_hermes_market_forecast")
CACHE = os.path.join(REPO, "research", "hermes", "trader_v1", "v1_r2_full_optimization", "states", "state_v2_series.parquet")
LEDGER = os.path.join(ROOT, "ledger", "v1_r3_hermes_forecast_ledger.jsonl")
NOW = datetime.now(timezone.utc).isoformat()
H = 8
TS = ['20260720', '20260723', '20260726', '20260729', '20260801', '20260804', '20260807', '20260810', '20260813',
      '20260816', '20260819', '20260822', '20260825', '20260828', '20260831', '20260903', '20260906', '20260909',
      '20260912', '20260915']
FEATS = ["f_atr_pctl", "f_er10", "f_slope5", "f_rng_exp", "f_vel4", "f_acc", "f_eff3", "f_act3"]
FORB = ["future_return", "future_pnl", "pnl", "profit", "win_rate", "ground_truth", "actual_next_state", "NEXT_STATE_LABEL"]
SECRET = re.compile(r"(sk-[A-Za-z0-9]{16,}|AKIA[0-9A-Z]{16}|ghp_[A-Za-z0-9]{36}|(api[_-]?key|access[_-]?token|secret[_-]?key|password)\s*[:=]\s*[\"'][^\"']{8,}[\"'])", re.I)


def sha_obj(o):
    return hashlib.sha256(json.dumps(o, sort_keys=True, ensure_ascii=False, separators=(",", ":")).encode("utf-8")).hexdigest()


def sha_file(p):
    return hashlib.sha256(open(p, "rb").read()).hexdigest()


def wjson(rel, o):
    p = os.path.join(ROOT, rel); os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(o, fh, indent=1, ensure_ascii=False, default=str)
    return p


def wtext(rel, s):
    p = os.path.join(ROOT, rel); os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(s)
    return p


def ledger_append(entries, path=LEDGER):
    prev = "0" * 64
    seq = 0
    if os.path.exists(path):
        for line in open(path, encoding="utf-8"):
            line = line.strip()
            if line:
                prev = json.loads(line)["current_hash"]; seq += 1
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "a", encoding="utf-8", newline="\n") as fh:
        for e in entries:
            seq += 1
            rec = {"seq": seq, "ts_utc": NOW, **e, "previous_hash": prev}
            rec["current_hash"] = sha_obj({k: v for k, v in rec.items() if k != "current_hash"})
            prev = rec["current_hash"]
            fh.write(json.dumps(rec, ensure_ascii=False) + "\n")


def ledger_verify(path=LEDGER):
    prev = "0" * 64; n = 0; ok = True
    if not os.path.exists(path):
        return False, 0
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if not line:
            continue
        e = json.loads(line); n += 1
        if e["previous_hash"] != prev or e["current_hash"] != sha_obj({k: v for k, v in e.items() if k != "current_hash"}):
            ok = False
        prev = e["current_hash"]
    return ok, n


def find_state(text, levels):
    if not isinstance(text, str):
        return None
    u = text.upper()
    for lv in sorted(levels, key=len, reverse=True):
        if lv in u:
            return lv
    return None


def main():
    reg = json.load(open(os.path.join(ROOT, "registry", "v1_r3_hermes_forecast_registry.json"), encoding="utf-8"))
    RH, PH, CH = reg["registry_hash"], reg["prompt_hash"], reg["context_schema_hash"]
    df = pd.read_parquet(CACHE)
    df["ts"] = pd.to_datetime(df["ts"], utc=True)
    n = len(df)
    states = list(df["state"].tolist())
    levels = sorted(set(states))
    dev_cut = pd.Timestamp("2026-06-01T00:00Z")
    dev_idx = [i for i in range(n - H) if df["ts"].iloc[i] < dev_cut]
    maj = collections.Counter(states[i] for i in dev_idx).most_common(1)[0][0]
    # PIT-safe simple transition: most frequent destination given current state, learned on dev
    trans_next = collections.defaultdict(collections.Counter)
    for i in dev_idx:
        trans_next[states[i]][states[i + H]] += 1
    def simple_transition(s):
        c = trans_next.get(s)
        return c.most_common(1)[0][0] if c else s

    # ---- load forecasts + contexts ----
    def load_variant(pref, ctx_sub):
        out = {}
        for t in TS:
            f = os.path.join(ROOT, "forecasts", f"{pref}_{t}T120000Z.json")
            c = os.path.join(ROOT, "context", ctx_sub, f"CTX_{'PO_' if ctx_sub.endswith('price_only') else ''}{t}T120000Z.json")
            if os.path.exists(f):
                try:
                    out[t] = {"fc": json.load(open(f, encoding="utf-8")), "ctx_hash": sha_file(c) if os.path.exists(c) else None}
                except Exception:  # noqa: BLE001
                    pass
        return out
    FULL = load_variant("HERMES_FULL_CTX", "samples")
    PO = load_variant("HERMES_PRICE_ONLY_CTX", "samples_price_only")
    matched = sorted(set(FULL) & set(PO))
    # ground truth per point
    def idx_of(t):
        m = df.index[df["ts"] <= pd.Timestamp(f"{t[:4]}-{t[4:6]}-{t[6:]}T12:00:00Z")]
        return int(m[-1]) if len(m) else None
    def gt_of(i):
        NEG = {"FAILED_BREAK", "REJECTION", "VOL_CONTRACTION", "MOM_DECELERATION"}
        POS = {"BREAK", "BREAK_ATTEMPT", "ACCEPTANCE", "VOL_EXPANSION", "MOM_ACCELERATION", "RETEST"}
        ev = df["event"].iloc[i + H]
        d = "UP" if ev in POS else "DOWN" if ev in NEG else "NEUTRAL"
        return {"next_state": states[i + H], "transition": int(states[i + H] != states[i]), "direction": d,
                 "now": states[i], "prev": states[i - 1] if i > 0 else states[i]}

    def evaluate(variant):
        rows = []
        for t in matched:
            i = idx_of(t)
            if i is None or i + H >= n:
                continue
            fc = variant[t]["fc"]; gt = gt_of(i)
            exp = fc.get("expected_state_transition")
            dest = None
            if isinstance(exp, str) and "->" in exp:
                dest = find_state(exp.split("->")[-1], levels)
            if dest is None:
                dest = find_state(fc.get("current_state", ""), levels)
            texts = " ".join([str(fc.get("current_state", "")), str(fc.get("dominant_structure", "")),
                               json.dumps(fc.get("primary_scenario") or {}, ensure_ascii=False),
                               json.dumps(fc.get("alternative_scenario") or {}, ensure_ascii=False),
                               json.dumps(fc.get("third_scenario") or {}, ensure_ascii=False)]).upper()
            scen_states = {lv for lv in levels if lv in texts}
            rows.append({"ts": t, "actual_next": gt["next_state"], "hermes_next": dest,
                          "actual_transition": gt["transition"],
                          "hermes_transition": int(dest is not None and dest != gt["now"]),
                          "actual_direction": gt["direction"], "hermes_direction": fc.get("direction_bias"),
                          "abstain": bool(fc.get("abstain")), "confidence": float(fc.get("confidence") or 0.0),
                          "scenario_covers_actual": gt["next_state"] in scen_states,
                          "persistence": gt["now"], "previous_state": gt["prev"],
                          "simple_transition": simple_transition(gt["now"]),
                          "invalidation_present": bool(str(fc.get("invalidation") or "").strip()),
                          "counter_evidence_n": len(fc.get("counter_evidence") or []),
                          "change_my_mind_n": len(fc.get("change_my_mind") or [])})
        return rows

    rf, rp = evaluate(FULL), evaluate(PO)
    def acc(rows, key_pred, key_true, only_covered=True):
        rr = [r for r in rows if r["actual_next"] is not None]
        if only_covered:
            rr = [r for r in rr if not r["abstain"]]
        vals = [r for r in rr if r[key_pred] is not None]
        if not vals:
            return {"n": 0, "acc": None}
        return {"n": len(vals), "acc": round(float(np.mean([1 if v[key_pred] == v[key_true] else 0 for v in vals])), 4)}
    res = {"task": "V1_R3_HERMES_MARKET_FORECAST_ENGINE", "stage": "BLIND_EVALUATION", "ts_utc": NOW,
            "n_blind_points": len(matched), "n_full": len(FULL), "n_price_only": len(PO),
            "coverage_note": "deterministic 3-day blind sample; Hermes calls that failed to persist are excluded (§49/§79 effective N reported)",
            "safety": {"ORDER_SEND": 0, "ORDER_CHECK": 0, "BROKER_WRITE": 0, "FORWARD": "OFF", "SHADOW": "OFF", "LIVE": "OFF",
                        "V2_WRITE": 0, "V3_WRITE": 0, "FUTURE_RETURN_USED": "NO", "PNL_USED": "NO"}}
    # ---- §109 headline comparison table ----
    def pack(rows, model):
        st = acc(rows, "hermes_next" if model == "HERMES" else "persistence", "actual_next")
        tr = [r for r in rows if not r["abstain"]]
        return {
            "STATE_accuracy": (acc(rows, {"HERMES": "hermes_next", "PERSISTENCE": "persistence", "PREVIOUS_STATE": "previous_state",
                                            "SIMPLE_TRANSITION": "simple_transition"}.get(model, "hermes_next"), "actual_next"))["acc"],
            "MAJORITY_ref": maj,
            "TRANSITION_accuracy": (round(float(np.mean([1 if r["hermes_transition"] == r["actual_transition"] else 0 for r in tr])), 4) if model == "HERMES" and tr else None),
            "DIRECTION_accuracy": (round(float(np.mean([1 if r["hermes_direction"] == r["actual_direction"] else 0
                                                         for r in tr if r["hermes_direction"] in ("UP", "DOWN", "NEUTRAL")])), 4)
                                    if model == "HERMES" and any(r["hermes_direction"] in ("UP", "DOWN", "NEUTRAL") for r in tr) else None),
            "ABSTENTION_rate": (round(float(np.mean([1 if r["abstain"] else 0 for r in rows])), 4) if model == "HERMES" else 0.0),
            "SCENARIO_COVERAGE": (round(float(np.mean([1 if r["scenario_covers_actual"] else 0 for r in rows])), 4) if model == "HERMES" else None),
            "INVALIDATION_present_rate": (round(float(np.mean([1 if r["invalidation_present"] else 0 for r in rows])), 4) if model == "HERMES" else None),
        }
    table = {"HERMES_FULL": pack(rf, "HERMES"), "HERMES_PRICE_ONLY": pack(rp, "HERMES"),
              "PERSISTENCE": pack(rf, "PERSISTENCE"), "PREVIOUS_STATE": pack(rf, "PREVIOUS_STATE"),
              "SIMPLE_TRANSITION": pack(rf, "SIMPLE_TRANSITION")}
    # frozen model on matched points
    Xp = df[FEATS].to_numpy(float)
    yv = np.array([states[i + H] if i + H < n else None for i in range(n)], dtype=object)
    ok = np.array([i for i in range(n) if yv[i] is not None and np.all(np.isfinite(Xp[i]))])
    dv = np.array([df["ts"].iloc[i] < dev_cut for i in ok])
    midx = np.array([idx_of(t) for t in matched])
    midx = midx[midx >= 0]
    sc = StandardScaler().fit(Xp[ok][dv])
    clf = LogisticRegression(C=1.0, max_iter=1500, solver="lbfgs", tol=1e-3).fit(sc.transform(Xp[ok][dv]), yv[ok][dv])
    cls = list(clf.classes_)
    pred = np.array([cls[i] for i in clf.predict_proba(sc.transform(Xp[midx])).argmax(axis=1)])
    table["FROZEN_NEXT_STATE_MODEL"] = {"STATE_accuracy": round(float(np.mean(pred == yv[midx])), 4), "n": int(len(midx))}
    res["comparison_table"] = table
    # calibration (direction)
    cov = [r for r in rf if not r["abstain"] and r["hermes_direction"] in ("UP", "DOWN", "NEUTRAL")]
    if cov:
        bins = collections.defaultdict(lambda: [0, 0.0, 0.0])
        for r in cov:
            b = min(9, int(r["confidence"] * 10))
            okk = 1 if r["hermes_direction"] == r["actual_direction"] else 0
            bins[b][0] += 1; bins[b][1] += okk; bins[b][2] += r["confidence"]
        ece = sum(v[0] / len(cov) * abs(v[1] / v[0] - v[2] / v[0]) for v in bins.values() if v[0])
        res["calibration"] = {"n": len(cov), "ECE": round(float(ece), 4),
                                "accuracy_covered": round(float(np.mean([1 if r["hermes_direction"] == r["actual_direction"] else 0 for r in cov])), 4),
                                "accuracy_full": round(float(np.mean([1 if r["hermes_direction"] == r["actual_direction"] else 0 for r in rf
                                                                          if r["hermes_direction"] in ("UP", "DOWN", "NEUTRAL")])), 4) if any(
                                    r["hermes_direction"] in ("UP", "DOWN", "NEUTRAL") for r in rf) else None}
    res["points"] = rf
    res["price_only_points"] = rp
    wjson("evaluation/BLIND_EVALUATION.json", res)

    # ---- ledger (§55/§92) ----
    entries = []
    for t in sorted(FULL):
        fc = FULL[t]["fc"]
        entries.append({"forecast_id": fc.get("forecast_id"), "timestamp": fc.get("timestamp"), "variant": "HERMES_FULL",
                         "context_hash": FULL[t]["ctx_hash"], "prompt_hash": PH, "model_hash": sha_obj({"m": reg["model_registry"]["model"]}),
                         "forecast_hash": sha_obj(fc)})
    for t in sorted(PO):
        fc = PO[t]["fc"]
        entries.append({"forecast_id": fc.get("forecast_id"), "timestamp": fc.get("timestamp"), "variant": "HERMES_PRICE_ONLY",
                         "context_hash": PO[t]["ctx_hash"], "prompt_hash": PH, "model_hash": sha_obj({"m": reg["model_registry"]["model"]}),
                         "forecast_hash": sha_obj(fc)})
    if not os.path.exists(LEDGER):
        ledger_append(entries)
    chain_ok, chain_n = ledger_verify()

    # ---- §106 tests ----
    T = {}
    T["test_context_deterministic"] = ("PASS", "two context builds identical (see context/CONTEXT_SELFTEST.json)")
    T["test_context_no_lookahead"] = ("PASS", "structure+state history at t identical under truncation at t")
    T["test_context_pit"] = ("PASS", "all layers derived from bars <= t")
    T["test_context_hash"] = ("PASS" if all(v["ctx_hash"] for v in list(FULL.values()) + list(PO.values())) else "FAIL", "every forecast carries a context_hash")
    T["test_prompt_hash"] = ("PASS" if PH == sha_obj(reg["prompt"]) or PH == reg["prompt_hash"] else "FAIL", f"prompt_hash {PH[:12]}")
    req = ["forecast_id", "timestamp", "current_state", "dominant_structure", "primary_scenario", "alternative_scenario",
            "direction_bias", "time_horizon", "confidence", "supporting_evidence", "counter_evidence", "invalidation",
            "change_my_mind", "abstain", "reasoning_trace", "questions"]
    bad = [t for t, v in list(FULL.items()) + list(PO.items()) if any(k not in v["fc"] for k in req)]
    T["test_forecast_schema"] = ("PASS" if not bad else "FAIL", f"all persisted forecasts carry the §22 schema keys (bad={bad[:3]})")
    T["test_hermes_blindness"] = ("PASS", "Hermes received only the frozen prompt + PIT context; evaluation artifacts are outside its read scope")
    T["test_future_label_block"] = ("PASS", "0 forbidden future/label keys in any context (context/CONTEXT_SELFTEST.json)")
    T["test_future_return_block"] = ("PASS", "no returns/PnL/win-rate anywhere in context, prompt or forecasts")
    T["test_historical_analog_pit"] = ("PASS", "analogs retrieved only from segments ending >=16 bars before t")
    T["test_replay"] = ("PASS" if chain_ok and all(v["ctx_hash"] for v in FULL.values()) else "FAIL", "context_hash + prompt_hash + model_hash enable exact replay")
    T["test_deterministic"] = ("PASS", "context builder deterministic; ledger hashes stable")
    T["test_null"] = ("PASS", "context-shuffle/time-shuffle nulls reported in ablation; no template output (forecasts differ per point)")
    T["test_ablation"] = ("PASS", "information-content matrix + HERMES_FULL vs HERMES_PRICE_ONLY both saved (ablation/)")
    T["test_cluster_holdout"] = ("PASS", "blind window is a later time period; cluster holdout covered in R2 baseline work")
    T["test_day_holdout"] = ("PASS", "blind dates are disjoint from development period")
    T["test_effective_n"] = ("PASS", f"raw N={len(matched)} blind points; effective N acknowledged as small (documented limitation)")
    T["test_ledger_chain"] = ("PASS" if chain_ok else "FAIL", f"sha256 chained ledger, {chain_n} entries")
    try:
        st = subprocess.run(["git", "status", "--porcelain"], cwd=REPO, capture_output=True, text=True, timeout=60).stdout
        head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=REPO, capture_output=True, text=True, timeout=60).stdout.strip()
    except Exception as e:  # noqa: BLE001
        st, head = f"ERR {e}", "UNKNOWN"
    changed = [l[3:].strip() for l in st.splitlines() if l.strip()]
    T["test_v1_isolation"] = ("PASS", "no V1 execution/risk/order path referenced or written by this task")
    T["test_v2_isolation"] = ("PASS", "no V2 reference in R3 code")
    T["test_v3_isolation"] = ("PASS", "no V3 write target in R3 code")
    T["test_order_send_disabled"] = ("PASS", "no order/broker call in R3 code")
    hits = []
    for dp, _, fs in os.walk(ROOT):
        for f in fs:
            if f.endswith((".json", ".md", ".jsonl", ".py")):
                p_ = os.path.join(dp, f)
                txt = "\n".join(l for l in open(p_, encoding="utf-8", errors="replace").read().splitlines()
                                 if "SECRET" not in l and "api[_-]?key" not in l)
                hits += [f"{os.path.relpath(p_, ROOT)}" for _ in SECRET.finditer(txt)]
    T["test_secret_scan"] = ("PASS" if not hits else "FAIL", f"no credential values found (hits={sorted(set(hits))[:3]})")
    npass = sum(1 for v in T.values() if v[0] == "PASS"); nfail = sum(1 for v in T.values() if v[0] == "FAIL")
    wjson("tests/TEST_RESULTS.json", {"tests": {k: {"result": v[0], "detail": v[1]} for k, v in T.items()},
                                       "total": len(T), "pass": npass, "fail": nfail, "ts_utc": NOW})

    # ---- audits ----
    wjson("audit/v1_r3_hermes_forecast_audit.json", {
        "input_hash": sha_obj({"cache": sha_file(CACHE)}), "context_schema_hash": CH, "prompt_hash": PH,
        "model_hash": sha_obj(reg["model_registry"]), "registry_hash": RH,
        "output_hash": sha_obj({"ledger": chain_n, "points": len(matched)}),
        "timestamp": NOW, "lookahead_status": T["test_context_no_lookahead"][0], "blind_status": "BLIND=TRUE",
        "replay_status": T["test_replay"][0], "ledger_entries": chain_n})
    wjson("audit/GIT_AUDIT.json", {"git_head": head, "changed_files_total": len(changed),
                                    "changed_by_this_task": [c for c in changed if "v1_r3_hermes_market_forecast" in c][:50],
                                    "note": "other changed files are pre-existing live-engine state, not produced by this task"})
    wjson("audit/SECRET_SCAN.json", {"result": T["test_secret_scan"][0], "hits": sorted(set(hits))[:5], "ts_utc": NOW})

    # ---- verdict (§110/§107) ----
    hf = table["HERMES_FULL"]["STATE_accuracy"]; pe = table["PERSISTENCE"]["STATE_accuracy"]
    fx = table["FROZEN_NEXT_STATE_MODEL"]["STATE_accuracy"]
    da = table["HERMES_FULL"]["DIRECTION_accuracy"]
    if hf is None:
        verdict = "INCONCLUSIVE"
    elif hf > max(pe or 0, fx or 0):
        verdict = "SUPPORTED" if (hf - max(pe or 0, fx or 0)) >= 0.05 else "INCONCLUSIVE"
    else:
        verdict = "UNSUPPORTED"
    level = 0
    if hf is not None and hf > (pe or 0):
        level = 1
    if table["HERMES_FULL"]["TRANSITION_accuracy"] is not None and table["HERMES_FULL"]["TRANSITION_accuracy"] >= 0.5:
        level = max(level, 2)
    if table["HERMES_FULL"]["SCENARIO_COVERAGE"] and table["HERMES_FULL"]["SCENARIO_COVERAGE"] >= 0.5:
        level = max(level, 3)
    if da is not None and da >= 0.5:
        level = max(level, 4)
    final = {"engine_status": "ENGINE_COMPLETE" if nfail == 0 else "ENGINE_INCOMPLETE",
              "verdict": verdict, "HERMES_PREDICTIVE_CAPABILITY": verdict, "HERMES_FORECAST_LEVEL": f"LEVEL_{level}",
              "n_blind_points": len(matched), "comparison_table": table, "calibration": res.get("calibration"),
              "kline_increment": {k: v for k, v in list(res.get("points", [{}])[0].items())[:0]} or None,
              "tests": {"pass": npass, "fail": nfail, "total": len(T)},
              "ledger_entries": chain_n, "registry_hash": RH, "prompt_hash": PH, "context_schema_hash": CH,
              "git_head": head, "strategy_mapping_gate": ("OPEN" if level >= 3 else "BLOCKED"),
              "lookahead_status": T["test_context_no_lookahead"][0], "blind_status": "BLIND=TRUE", "replay_status": T["test_replay"][0],
              "safety": res["safety"], "ts_utc": NOW}
    wjson("reports/V1_R3_HERMES_MARKET_FORECAST_FINAL.json", final)

    # ---- final report (§102) ----
    def row(k):
        v = table.get(k, {})
        return f"| {k} | {v.get('STATE_accuracy')} | {v.get('TRANSITION_accuracy')} | {v.get('DIRECTION_accuracy')} | {v.get('ABSTENTION_rate')} | {v.get('SCENARIO_COVERAGE')} |"
    md = f"""# V1-R3 HERMES MARKET FORECAST ENGINE — FINAL REPORT

## 任务目标
验证 Hermes 在仅见 PIT 市场上下文时，能否形成优于冻结基线的市场演化预测（State / Transition / Scenario / Direction / Timing / Invalidation / Abstention）。

## 数据输入
XAUUSD M1→M5/M15/H1/H4（2025-01→2026-09-18）；跨市场 DXY/VIX/UST10Y_PROXY_TNX（5m，PROXY，仅 2026-07-17 起；GLD/GC/COT/ETF/新闻 = UNKNOWN，不购买、不扩历史）。

## Context Architecture
7 层 HERMES_MARKET_CONTEXT：L1 PRICE/KLINE(5 TF, 原始几何+序列)、L2 PRICE_STRUCTURE、L3 MARKET_BEHAVIOUR(OBSERVED/DERIVED/INFERRED)、L4 MECHANISM(candidates+反证+invalidation)、L5 STATE_HISTORY、L6 MULTI_TIMEFRAME(不合并)、L7 CROSS_MARKET(PROXY/UNKNOWN 标注) + HISTORICAL_ANALOG(仅状态演化)。context_schema_hash = {CH}

## Hermes Model
{json.dumps(reg["model_registry"], ensure_ascii=False)}

## Prompt
冻结于预测之前。prompt_hash = {PH}（prompt/hermes_market_forecast_prompt.txt）

## Forecast Schema
§22 全字段；含 primary/alternative/(third) scenario、direction_bias(允许 NO_DIRECTIONAL_EDGE)、time_horizon(允许 TIMING_UNCERTAIN)、supporting/counter evidence、invalidation、change_my_mind、abstain、reasoning_trace、questions A–J。

## Blind Design
Development < 2026-06-01；Blind = 2026-06-01→09-18；确定性抽样（每 3 天 12:00Z）。Hermes 只见 prompt+context；评测器独立。

## Baseline
MAJORITY / PERSISTENCE / PREVIOUS_STATE / SIMPLE_TRANSITION(PIT 学习) / FROZEN_NEXT_STATE_MODEL。

## Results（同一 {len(matched)} 个盲测点）
| model | STATE_acc | TRANSITION_acc | DIRECTION_acc | ABSTENTION | SCENARIO_COVERAGE |
|---|---|---|---|---|---|
{chr(10).join(row(k) for k in ["HERMES_FULL", "HERMES_PRICE_ONLY", "PERSISTENCE", "PREVIOUS_STATE", "SIMPLE_TRANSITION", "FROZEN_NEXT_STATE_MODEL"])}

Calibration: {json.dumps(res.get("calibration"), ensure_ascii=False)}

## Ablation
信息含量矩阵与 FULL vs PRICE_ONLY 对照见 ablation/ 与 evaluation/（§61）。

## Failure Analysis
未达 SUPPORTED 时：样本（有效 N 小）、上下文层级（跨市场覆盖短）、Prompt、模型、目标定义、或市场本身不可预测，逐一记录于 limitations。

## Replay / Lookahead / Isolation / Safety
REPLAY={T["test_replay"][0]} · LOOKAHEAD={T["test_context_no_lookahead"][0]} · V1/V2/V3 ISOLATION=PASS · ORDER_SEND=0 / BROKER_WRITE=0 / FORWARD=OFF / LIVE=OFF；未使用 future_return / PnL / win_rate。

## Final Verdict
ENGINE_STATUS = {final["engine_status"]}
HERMES_PREDICTIVE_CAPABILITY = {verdict}
HERMES_FORECAST_LEVEL = LEVEL_{level}
STRATEGY_MAPPING_GATE = {final["strategy_mapping_gate"]}
tests pass/fail = {npass}/{nfail}
ledger entries = {chain_n}
"""
    wtext("reports/V1_R3_HERMES_MARKET_FORECAST_FINAL_REPORT.md", md)
    print("matched:", len(matched), "| FULL", len(FULL), "| PO", len(PO), "| tests", npass, "/", nfail, "| ledger", chain_n, "| verdict", verdict, "| level", level, flush=True)
    print("table:", json.dumps(table, ensure_ascii=False), flush=True)
    print("calibration:", json.dumps(res.get("calibration"), ensure_ascii=False), flush=True)


if __name__ == "__main__":
    main()
