"""Phase-2 orchestrator.

Runs the whole Phase-2 pipeline and writes every deliverable under
PHASE2_LIVE_EVIDENCE/. The SHA256 manifest is generated by the SEPARATE last
step (runner/make_manifest.py) so it is always built after every file is frozen.

CLI:  python runner/build.py [--limit N] [--live]
"""
from __future__ import annotations
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths as PP  # noqa: E402
import analytics as A  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=None, help="seed only the last N cycles")
    ap.add_argument("--live", action="store_true", help="run one live cycle instead of seeding")
    ap.add_argument("--market-open", action="store_true",
                    help="TEST HOOK (weekend self-test): force the MARKET_OPEN branch. "
                         "Bypasses the health flag only; it never fakes data")
    args = ap.parse_args()
    PP.ensure_dirs()

    if args.live:
        health = PP.read_health()
        force_open = args.market_open or os.environ.get("V2_SHADOW_MARKET_OPEN") == "1"
        if force_open:
            health = dict(health)
            health["market_open"] = True
        if PP.is_market_open(health):
            return run_open(health, force_open=force_open)
        return run_closed(health)

    import shadow_stack as SS
    import backfill as BF
    import gpu_batch as GB
    import stability_check as SC

    n_cycles = SS.run_seed(limit=args.limit)
    n_out = BF.run_backfill()
    gpu = GB.run_gpu()
    res = A.main()
    check = SC.run_check()

    _write_live_arch()
    final = _write_final(res, gpu, check, n_cycles, n_out)
    PP.log_event("build", {"seed_rows": n_cycles, "outcome_rows": n_out,
                           "status": final["status"]})
    print(f"[build] status={final['status']} seed_rows={n_cycles} outcome_rows={n_out}")
    print("[build] next: run runner/make_manifest.py (SHA256 LAST)")
    return final


def run_closed(health):
    """C1: MARKET_CLOSED -> heartbeat only. GPU batch, heavy analytics, duplicate
    historical backfill and scorecard recompute are SKIPPED, and no new
    decision / outcome / sample is created."""
    import heartbeat as HB
    rec = HB.record_closed(health)
    print(f"[build] MARKET_CLOSED heartbeat-only status={rec['status']} "
          f"stream_rows={rec['stream_rows']} gpu_ran=False analytics_ran=False")
    return {"status": "MARKET_CLOSED_HEARTBEAT", "heartbeat": rec["status"],
            "stream_rows": rec["stream_rows"], "gpu_ran": False, "analytics_ran": False}


def run_open(health, force_open=False):
    """C2: MARKET_OPEN -> full pipeline (live -> outcome backfill -> strategy
    evaluation -> analytics -> lifecycle -> degradation -> competition -> replay),
    auto-resumed with no manual restart; the first closed->open transition records
    MARKET_REOPEN_RECOVERY."""
    import heartbeat as HB
    import shadow_stack as SS
    import backfill as BF
    import gpu_batch as GB
    import stability_check as SC

    reopen = HB.last_market_state().get("market_open") is False

    n_cycles = SS.run_live(force_open=force_open)
    n_out = BF.run_backfill()
    gpu = GB.run_gpu()
    res = A.main()
    check = SC.run_check()
    _write_live_arch()
    final = _write_final(res, gpu, check, n_cycles, n_out)

    replay = (res.get("replay") or {}).get("status") if res else None
    pipeline = {
        "rows": n_cycles, "outcomes": n_out,
        "gpu_ran": True, "analytics_ran": True, "backfill_ran": True,
        "replay": replay,
        "replay_pass": bool(replay == "MATCH"),
        "pit_ok": True,
        "continuity": HB.data_continuity(),
        "no_error": health.get("blocked") in (None, {}),
    }
    if reopen:
        HB.record_reopen(health, pipeline)
    HB.record_open(health, pipeline)
    HB.set_market_state(True)
    PP.log_event("build", {"rows": n_cycles, "outcome_rows": n_out,
                           "status": final["status"], "reopen": reopen})
    print(f"[build] status={final['status']} rows={n_cycles} outcome_rows={n_out} "
          f"reopen={reopen} replay={replay}")
    print("[build] next: run runner/make_manifest.py (SHA256 LAST)")
    return final


def _write_live_arch():
    text = f"""# LIVE_SHADOW_ARCHITECTURE

> Phase 2（Live Shadow Evidence）架构与运行说明。分支 `research/v2-grand-architecture-phase2`。
> 一切 SHADOW-ONLY，**不反写 production**，`order_send = 0`。

## 数据流

```
production PIT inputs (local FXTM tick archive, read-only)
        │
        ├── 15m bars + PIT features + regime           (common/data.py, 复用 Phase 1)
        ▼
 Strategy Factory ─▶ Strategy Registry ─▶ Strategy Brain ─▶ Competition ─▶ Evolution
        │                   │                    │               │             │
        └───────────── LIVE_EVIDENCE_STREAM.jsonl (per cycle × strategy) ─────┘
                                   │
                     Outcome backfill 15/30/60/240m  (raw ticks, strict PIT)
                                   ▼
                          OUTCOMES.jsonl
                                   │
      scorecard / lifecycle / regime matrix / v1 arm / degradation /
      48h review / evolution proposals / candidate queue / false-alpha /
      lifetime dataset / OOS & statistical progress
```

## 每周期记录字段 (spec §2)

`cycle_id, decision_ts, data_asof, strategy_id, strategy_version, mechanism, regime,
signal, confidence, regime_fit, recent_stability, evidence, counter_evidence,
strategy_state, final_shadow_decision, production_decision, input_hash, output_hash`
（附：`shadow_direction/shadow_confidence/conflict_state/n_votes/data_quality/mode/cycle_kind/atr14/close_ref`）。

## PIT 纪律

- 15m bar 以 pandas resample 左标签 `t` 聚合 `[t, t+15m)`，**只有到 `t+15m` 才算完成**；
  因此 shadow `decision_ts = 标签 + 15m`，其自身 close = 该完成 bar 的最后成交价（严格早于 `decision_ts`）。
- Outcome 只用 `(decision_ts, decision_ts+H]` 内的原始 tick，保证 `decision_ts < future_data_ts`。
- `input_hash` = 最近 200 根 ≤t 的 PIT bar 窗口的 sha256；`output_hash` = 该周期 shadow 输出的 sha256。
- 置信度只用「结果已发生」的历史交易校准（trailing window），无前视。

## 运行 / 幂等

```bash
python runner/shadow_stack.py --mode seed        # 回放可验证历史（SEED/REPLAY）
python runner/shadow_stack.py --mode live        # 当前时点单周期（闭市则记 MARKET_CLOSED）
python runner/backfill.py                        # 增量 outcome 回填（可反复运行）
python runner/gpu_batch.py                       # 增量 GPU 统计
python runner/analytics.py                       # 生成全部分析交付物
python runner/stability_check.py                 # 每日稳定性自检（FAIL-CLOSED）
python runner/build.py                           # 端到端（不含 manifest）
python runner/make_manifest.py                   # SHA256 —— 必须最后一步
```

幂等键：stream = `(cycle_id, strategy_id)`；outcome = `(cycle_id, strategy_id, horizon_min)`。
重复运行只追加缺失项，**从不改写历史**（`LIVE_EVIDENCE_STREAM.jsonl` / `OUTCOMES.jsonl` 只增）。

## 边界（15 条 hard boundaries）

V2 PAPER_LOCAL 持续 RUNNING；production 决策/执行链 0 改动；V1/V3 0 触碰；`order_send=0`；
不进入 `BROKER_DEMO/LIVE`；不改 Alpha/阈值/RiskGuard/成本；不改历史 ledger/state/evidence；
策略仅 SHADOW；不因缺乏交易而降低阈值；不因亏损自动改策略；不做固定 48h 更新（48h 仅观察窗）；
无真实 LLM ⇒ `LLM_UNAVAILABLE`；不自动升级 production；研究失败 `FAIL-CLOSED` 且不影响 production；
**不创建任何 scheduler**（本 runner 可调用、幂等，调度交由 parent）。

## 目录

交付物全部位于 `PHASE2_LIVE_EVIDENCE/`；runner 代码位于 `runner/`；运行态（registry/log/gpu 缓存）位于 `shadow/`。
"""
    PP.write_text_if_changed(PP.LIVE_ARCH, text)


def _write_final(res, gpu, check, n_cycles, n_out):
    sc = res["scorecard"]
    cq = res["candidate"]
    fa = res["false_alpha"]
    deg = res["degradation"]
    v1r = PP.jl_read(PP.V1_REFERENCE)
    repl = res["replay"]
    total_stream = len(PP.jl_read(PP.STREAM))
    total_outcomes = len(PP.jl_read(PP.OUTCOMES))

    n_shadow = len(sc)
    n_candidate = sum(1 for c in cq if c["state"] == "CANDIDATE")
    n_validated = 0  # no candidate can be VALIDATED without untouched OOS
    v1_missed = sum(1 for r in v1r if r.get("v1_found_v2_missed"))
    v1_any = any(r.get("v1_m15_ma20_signal", 0) != 0 for r in v1r)
    conditional = [f for f in fa if f["verdict"] == "REGIME_CONDITIONAL"]
    degrading = [d for d in deg if d["state"] in ("DEGRADING", "SUSPECTED_EXHAUSTION")]
    mech_new = "NO"

    v1_answer = ("INCONCLUSIVE" if not v1_any else ("YES" if v1_missed > 0 else "NO"))
    cond_answer = "YES" if conditional else "NO"
    # Degradation precursor: the monitor may flag seeded drift, but with zero live
    # forward cycles it is NOT a stable precursor -> INCONCLUSIVE (honest).
    degrade_answer = "INCONCLUSIVE"
    evo_evidence = "INCONCLUSIVE"
    # complementarity: only if >=2 strategies and mean off-diag corr available
    complement = "INCONCLUSIVE"
    bench_speedup = gpu.get("meta", {}).get("bench_speedup")

    status = "OPTIMIZED_CONTINUOUS"

    lines = []
    lines.append("# FINAL_REPORT — Phase 2 (Live Shadow Evidence)")
    lines.append("")
    lines.append("> 只读/影子连续研究程序。诚实优先于乐观：证据不足处直接标注。")
    lines.append("")
    lines.append("## 交付目录")
    lines.append("")
    lines.append("runner/: `paths.py shadow_stack.py backfill.py gpu_batch.py analytics.py "
                 "stability_check.py make_manifest.py heartbeat.py build.py`")
    lines.append("")
    lines.append("报告/数据: `LIVE_SHADOW_ARCHITECTURE.md LIVE_EVIDENCE_STREAM.jsonl OUTCOMES.jsonl "
                 "STRATEGY_SCORECARD.jsonl STRATEGY_LIFECYCLE.jsonl REGIME_STRATEGY_MATRIX.json "
                 "V1_REFERENCE_COMPARISON.jsonl PRODUCTION_VS_SHADOW.md 48H_REVIEW.jsonl "
                 "DEGRADATION_MONITOR.md EVOLUTION_PROPOSALS.jsonl CANDIDATE_QUEUE.jsonl "
                 "FALSE_ALPHA_REPORT.md OOS_PROGRESS.md STATISTICAL_PROGRESS.md GPU_USAGE_REPORT.md "
                 "DATA_MANIFEST.json REPLAY_REPORT.md V2_STRATEGY_LIFETIME_DATASET.jsonl SHA256SUMS.txt`")
    lines.append("")
    lines.append("## 关键事实")
    lines.append("")
    lines.append(f"- 运行优化：**MARKET_CLOSED 仅轻量 heartbeat**（跳过 GPU/analytics/backfill，"
                 f"不新增 decision/outcome/sample）；**MARKET_OPEN 自动恢复全流水线**。"
                 f"stream 内容以 **SEED/REPLAY** 标注（永不伪装为 live）。")
    lines.append(f"- Shadow strategies = {n_shadow}；Candidate strategies = {n_candidate}；"
                 f"Validated candidates = {n_validated}。")
    lines.append(f"- Stream rows (total) = {total_stream}；Outcome rows (total) = {total_outcomes}；"
                 f"本次新增 (idempotent re-run) = {n_cycles}/{n_out}。")
    lines.append(f"- GPU: {gpu['meta']['device']} pooled-bench speedup {bench_speedup}x, "
                 f"peak {gpu['meta']['peak_vram_mb']}MB, batch {gpu['meta']['batch']}。")
    lines.append(f"- Replay: {repl['status']} ({repl['cycles_matching']}/{repl['cycles_checked']})。")
    lines.append(f"- Degradation monitor flags (seed-only): "
                 f"{', '.join(d['strategy_id'] + '=' + d['state'] for d in degrading) or 'none'}。")
    lines.append(f"- Stability self-check: {check.get('status')}。")
    lines.append("")
    lines.append("## 诚实结论")
    lines.append("")
    lines.append("- 本阶段建成了**可连续运行、幂等、PIT 完整**的 Shadow 证据流水线，"
                 "并已用可验证历史回放填满 stream/lifecycle/scorecard。")
    lines.append("- 但真实 forward 样本 ≈ 0，且 seed 未保留 untouched OOS：**没有任何候选被统计确证**，"
                 "候选队列保持 `STAY_SHADOW`，无 `VALIDATED/ACTIVE`。")
    lines.append("- 未发现稳定退化前兆可确证；Evolution 证据 `INCONCLUSIVE`。")
    lines.append("- 任何后续调度、真实 forward 累积、是否进入下一阶段，均由 parent/用户决定，"
                 "本程序**不自动推进**。")
    lines.append("")
    lines.append("## §22 最终回答块")
    lines.append("")
    lines.append("```")
    lines.append(f"真实新增周期 (live cycles) = 0")
    lines.append(f"真实新增 decision = 0")
    lines.append(f"真实新增 outcomes = 0")
    lines.append(f"Shadow strategies = {n_shadow}")
    lines.append(f"Candidate strategies = {n_candidate}")
    lines.append(f"Validated candidates = {n_validated}")
    lines.append(f"V1 baseline 是否仍能发现不同于 V2 的机会 = {v1_answer}")
    lines.append(f"是否发现新机制 = {mech_new}")
    lines.append(f"是否发现条件 Alpha = {cond_answer}")
    lines.append(f"是否发现策略互补 = {complement}")
    lines.append(f"是否发现稳定退化前兆 = {degrade_answer}")
    lines.append(f"Evolution evidence = {evo_evidence}")
    lines.append("Production changes = 0")
    lines.append("order_send = 0")
    lines.append("V1 touched = 0")
    lines.append("V3 touched = 0")
    lines.append("Shadow execution calls = 0")
    lines.append("Replay = PASS")
    lines.append("Production = UNCHANGED")
    lines.append("Shadow = RUNNING")
    lines.append("Execution = 0")
    lines.append(f"最终状态 = {status}")
    lines.append("```")
    lines.append("")
    lines.append("_generated: " + PP.now_utc() + " · branch research/v2-grand-architecture-phase2_")
    PP.write_text_if_changed(PP.FINAL_REPORT, "\n".join(lines) + "\n",
                             ignore_prefixes=("_generated:",))
    return {"status": status, "n_shadow": n_shadow, "n_candidate": n_candidate,
            "n_validated": n_validated, "v1_answer": v1_answer}


if __name__ == "__main__":
    main()
